### PR TITLE
Linux build

### PR DESCRIPTION
**Pull request by c4llv07e**
Thomas uses cross-platform libraries, so this pull-request adds a host build on Linux.
At this stage I was only able to compile it, but there are errors in the runtime.

### CODE REVIEW

**Comment by c4llv07e** [comment]
It works now (at least IWOMM), but I haven't checked if it breaks Windows build, so please check it.

**Comment by c4llv07e** [comment]
I can't fix build errors without constantly editing new code, gcc and clang doesn't support parentheses initialization because [it is deprecated in C++11](https://stackoverflow.com/a/24837330) and there is no way to write a define macro or inline function.

**Comment by c4llv07e** [comment]
It is now working again, but in order for this to work, I had to add constructors for base classes like vec2 and range2. It's less convenient than just using initialization with curly braces, but it was [the only working option](https://www.youtube.com/watch?v=oi3VFYk5NOE&lc=UgxBXL7CUD1Kbkhj0RJ4AaABAg.9hY3ZL03-OA9hYBzhcOl8R).

**Comment by bigrando420** [comment]
The Linux compatibility seems dead in the water now unless we can figure out #2 

I'll get around to fixing up that `{}` constructor issue shortly.

**Comment by c4llv07e** [comment]
Ok

**Pull request closed without merging**
